---
title: "Pivot_Lobsters.rmd"
author: "KKC"
date: "1/27/2020"
output: html_document
---
```{r}
library(tidyverse)
library(readxl)
library(here)
library(skimr) # install.packages("skimr")
library(kableExtra)  # install.packages("kableExtra")

# read in lobsta data

lobsters <- read_xlsx(here("data", "lobsters.xlsx"),
                      skip = 4)

```
```

Viewing our data with skimr::
```
```{r}

# these are equivalent
skimr::skim(lobsters)
skim(lobsters)
```

#  Piviot Table
In R, Pivot tables are: `group_by() %>% summarize()`
'n() function will count observations
```{r}

# Group by Year
lobsters %>% 
  group_by(year)  %>% 
  summarize(count_by_year = n())
```
```{r}
# Group by year and site
lobsters %>% 
  group_by(year, site)  %>% 
  summarize(count_by_yearsite = n())

# Group by site and year
lobsters %>% 
  group_by(site, year)  %>% 
  summarize(count_by_siteyear = n())
```

```{r}
siteyear_sumary <- lobsters %>% 
  group_by(site, year) %>% 
  summarize(count_by_site_year = n(),
             mean_size_mm = mean(size_mm, na.rm=TRUE),
            sd_size_mm = sd(size_mm, na.rm=TRUE))
                            
```
Table formatting with 'kableExtra'::kable()"
```{r}
siteyear_sumary %>% 
  kable()
```
There are `r nrow(lobsters)` total lobsters included in this report.

##  Activity
1. build from our analyses: calculate the median lobster size for each site and year (hint: `size_mm~ and a function called `median()`
2. sync this to github

```{r}
site_year_median<-lobsters %>% 
  group_by(site, year) %>% 
  summarize(count_by_site_year = n(),
             median_size_mm = median(size_mm, na.rm=TRUE),
            sd_size_mm = sd(size_mm, na.rm=TRUE))

ggplot(data = site_year_median, aes(x = year, y = median_size_mm, color = site)) + 
  geom_line()
ggsave(here("figures", "lobster-plot.png"))
```




```



